### ISSUE TITLE
Retrying whole batch on single failure

### ISSUE THREAD

**Issue by mgibas** [serilog/serilog-sinks-periodicbatching#15]
So, for now when sending single message fail, whole batch is sent once again (doubling messages that where sent properly prior failure). Im wondering if its by design or I can spend some time to create PR to fix this ?

**Comment by skomis-mm** [comment]
@mgibas , from `PBS`'s point of view `EmitBatch(..)` is designed to be atomic so underlying sinks can post events efficiently and retry logic is implemented around it.

Another thing is just setting the `batchSize=1` won't necessarily help to throttle requests because within a timeframe window the queue can be filled with events that will exceed rate limit on actual send if `EmitBatch(..)` sends log events one-by-one.

One option to explore if you want to reuse existing logic is to set `batchSize=1` _and_ `queueLimit=1` with a period of `1s` for the `Slack` sink. Still not ideal on extreme cases but may just work.
But may be a better way is just implement sink from the scratch since it doesn't use batching and `PBS` don't have explicit throttle capability.
