### ISSUE TITLE
Feature Request: Durability option with backing file

### ISSUE THREAD

**Issue by jsearles** [serilog/serilog-sinks-periodicbatching#22]
I've noticed that a few of the sinks have support for additional durability for remote services to account for intermittent failure by logging to a file. I think this could be abstracted and baked into this library.

Sinks that implement this pattern include:
- https://github.com/serilog/serilog-sinks-seq
- https://github.com/serilog/serilog-sinks-loggly

**Comment by nblumhardt** [comment]
Thanks for the request, sorry a reply took so long (I'm not sure whether we discussed this elsewhere?)

So far, in my experience, the durable shipping option has been shaky - it's tricky to manage in multi-process scenarios, including most web servers, and so I've been hesitant to double down further on it.

Using _Serilog.Formatting.Compact_ and _Serilog.Formatting.Compact.Reader_, it might be possible to enable something very similar as a sink "wrapper".

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.DurableSink(
        "logs/buffer.clef",
        wt => wt.SomeOtherSink(...))
    .CreateLogger();
```

To do this today, you'd need to use reflection to call into `EmitBatchAsync()` directly on the wrapped sink, to circumvent setting the sink's timer - a bit hacky, but probably stable enough since `EmitBatchAsync()` is effectively un-breakable public API surface.

Anyone interested in helping to hack this together? It'd be an interesting experiment, and if it worked well, could help us pull a lot of duplicated code out of the Seq, Elasticsearch and Loggly sinks (and enable this as a new feature for others). We'd also then have the option of iterating faster on the durable shipping logic.

Finally, we could start paving the way for an `IBatchedLogEventSink` in Serilog proper, that would help with other tasks such as enabling "audit mode" for the sinks based on `PeriodicBatchingSink`.

**Comment by nblumhardt** [comment]
Closing as it doesn't look like there are any takers to help move this forwards, but I'm keen to explore it further if anyone passing by has the time to dig in :-)
