### ISSUE TITLE
Batch will not flush during thread abort

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-sinks-periodicbatching#25]
While considering this https://github.com/serilog/serilog-sinks-mssqlserver/issues/121 issue, I believe the "fail silently" catch block in this sink ([here](https://github.com/serilog/serilog-sinks-periodicbatching/blob/master/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L179)) and the same feature in the SQL sink's `EmitBatchAsync` method prevents the batch from flushing when an application is terminated due to a thread abort.

`ThreadAbortException` gets special treatment in that it is automatically re-thrown at the end of any `catch` block, which trips every `catch(Exception ex)` block in the call stack. The issue linked above shows self-log failure messages from both the SQL sink and the periodic batching sink because of this.

I think the solution might be for this sink to tolerate a `ThreadAbortException` (perhaps move the `OnTick` code into a separate private method and call it from both the `try` block and the thread abort `catch` block?) and for the SQL sink to do the same.

It might also be useful to continue emitting a self-log message clarifying it was a flush due to thread abort.

**Comment by skomis-mm** [comment]
@MV10 I think that this should be a client responsibility to make a proper cleanup. If PBS would handle `ThreadAbortException` because of domain unload then there is a possibility that flush operation will hang (remote server is temporarily unavailable etc) and then you can end up with `CannotUnloadAppDomainException` (after ~10 seconds or so) with all its ["goodness"](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unload?view=netframework-4.7.2#remarks):
> If the thread that could not be aborted eventually ends, the target domain is not unloaded. Thus, in the .NET Framework version 2.0 domain is not guaranteed to unload, because it might not be possible to terminate executing threads.

 So there is a bit of danger from logging library that could produce such side effect

**Comment by MV10** [comment]
@skomis-mm The problem with thread abort is that a client can't do a cleanup, it's like the threading version of a drive-by shooting. (Well, any catcher in the stack can cancel it, which is also weird, but that has other obvious problems.)

But it's enough of an edge-case that I won't lose any sleep over it. (I was probably in thread-abort-shell-shock after having dealt with that complex case at work after I went back to that SQL sink topic.) Thanks for taking the time to have a look here and over in SQL-land.
