### ISSUE TITLE
Timer should be stopped when there are no remaining events

### ISSUE THREAD

**Issue by mniak** [serilog/serilog-sinks-periodicbatching#44]
I think the timer should be disable when there ar no more events to be written/sent/emmited.

In a recent problem described in #43 (totally my fault) I got to perceive that the class `PeridodicBatchingSink` continues running even when there are no more events.

The _High CPU Usage_ problem I was facing was due to `period` being informed `TimeSpan.Zero`.
While I assume this was my fault, there were no reason to the timer to keep running when the log event count reaches zero.

It should be started again when next event comes.

Is this behavior _by-design_? Would it make any sense to improve this like described?

Thanks!

**Comment by skomis-mm** [comment]
Hi @mniak,

I beleive it is by design. Technically there is a [contract (OnEmpyBatch)](https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L337) that should be respected when there are no events in the batch.

 It wasn't designed to work with periods around the delta of zero. The whole point of this is to offload sending burst of events with batches and at ~constant pace.

**Comment by mniak** [comment]
> /// Allows derived sinks to perform periodic work without requiring additional threads
> /// or timers (thus avoiding additional flush/shut-down complexity).

Oh, I see.
Thank you very much for the attention!
