### ISSUE TITLE
OutOfMemory under stressed sinks

### ISSUE THREAD

**Issue by operezfuentes** [serilog/serilog-sinks-periodicbatching#6]
That's about returning to issue  https://github.com/serilog/serilog/issues/293, this issue was closed because durability method can be implemented in sinks. But we are returning to same problem:
- Generating more log events that sink can process (i.e. ElasticSearch node is down) generates memory increase because this events are retained in PeriodicBatchingSink._queue

This similar aproach is solved in nlog https://github.com/nlog/NLog/wiki/AsyncWrapper-target using _overflowAction_

Personally agree witn nlog aproach, why stress memory if simply we can drop the event without add to queue.

It's so easy as manage a similar property like PeriodicBatching.CanInclude (i.e. **CanEnqueue**) and check in every Emit method

Please, can you consider this issue in order I can open a PR?

**Comment by nblumhardt** [comment]
Hi Oscar,

Some help with this/a PR would definitely be appreciated.

It's probably worth mentioning https://github.com/serilog/serilog/pull/623 which was recently merged in order to reduce contention when enqueuing events - it would be great to preserve this property when addressing the queue-bounding requirement.

Regards,
Nick

**Comment by nblumhardt** [comment]
Though #11 provides the `queueLimit` argument to support this, sinks will need to be updated before it is applied. We could default to a reasonable bound in `PeriodicBatchingSink`, but this will still involve sink changes before the default can then be lifted. Thoughts?

**Comment by skomis-mm** [comment]
Not sure if it can be set with some const limit, because it depends on period that is already non-optional. I see in `Seq` sink the default is 2sec, for `MsSql` - 5sec. May be we can pass some kind of `period.TotalSeconds * 10000(00..)`?

**Comment by nblumhardt** [comment]
`period.TotalSeconds * 10000` sounds reasonable, but we could still end up dropping events in situations where we might not want to.

Let's say we're logging 1000 events/second at 2 second period (= 20,000 event buffer). The remote server needs to reboot and takes 5 minutes, 5 \* 60 \* 1000 = 300,000 events. Most machines could comfortably buffer that much so it seems like keeping the events is the right thing to do in that case.

Since appropriate buffer size depends on machine resources and utilization, perhaps opt-in is the only way to avoid surprises... Guess we need to add those parameters downstream.
